image:
  file: .gitpod.Dockerfile
tasks:
- before: >
    source ~/.bashrc
  init: |
    flutter upgrade
    flutter update-packages --force-upgrade
    npm -g install firebase-tools
    firebase --version
    firebase login --no-localhost
    gp sync-done flutter_install
- name: codelabs part
  init: |
    gp sync-await flutter_install
    read -p "Enter Your Flutter project name: " Flutter_ID
    case $Flutter_ID in
      "" | "friendlyeats-flutter" )
        git clone https://github.com/FirebaseExtended/codelab-friendlyeats-flutter.git $Flutter_ID
        cd $Flutter_ID
        firebase use --add
        flutter run -d web-server --no-resident # prebuilds the app
        ;;
      "friendlychat" )
        git clone https://github.com/firebase/codelab-friendlychat-web $Flutter_ID
        cd $Flutter_ID
        cd web
        firebase use --add
        firebase serve --only hosting
        # 左のshellにてwebディレクトリへ。以下左で実行
        # npm install
        # npm run start
        ;;
      * )
        flutter create $Flutter_ID
        cd $Flutter_ID
        firebase init
        firebase use --add
        flutter run -d web-server --no-resident # prebuilds the app
        ;;
    esac
    # flutter run -d web-server --web-renderer html
    # firebase deploy --only firestore:indexes
    # firebase deploy --only firestore:rules
    # flutter build web
    # firebase init hosting
    # firebase deploy --only hosting
  command: >
    flutter run -d web-server --web-renderer html --web-port=8080 --web-hostname=0.0.0.0
  openMode: split-right
ports:
- port: 8080
  onOpen: open-preview
vscode:
  extensions:
    - Dart-Code.dart-code
    - Dart-Code.flutter
